"""
Tool Executor

Executes tool calls generated by the planner.

Flow

Agent Plan
      │
      ▼
Tool Registry
      │
      ▼
Execute Tool
      │
      ▼
Collect Results
      │
      ▼
Execution Context
"""

from __future__ import annotations

import logging
from time import perf_counter

from .models import (
    ExecutionContext,
    ToolCall,
    ToolResult,
)

logger = logging.getLogger(__name__)


class ToolExecutor:
    """
    Executes registered tools.
    """

    def __init__(
        self,
        *,
        registry,
        context_manager,
    ):
        self.registry = registry
        self.context_manager = context_manager

    # ---------------------------------------------------------

    def execute(
        self,
        *,
        context: ExecutionContext,
        tool_call: ToolCall,
    ) -> ToolResult:
        """
        Execute a single tool.
        """

        start = perf_counter()

        logger.info(
            "Executing tool: %s",
            tool_call.tool.value,
        )

        try:

            tool = self.registry.get(
                tool_call.tool,
            )

            #
            # Every tool implements execute(...)
            #
            data = tool.execute(
                context=context,
                **tool_call.input,
            )

            result = ToolResult(
                tool=tool_call.tool,
                success=True,
                data=data,
            )

        except Exception as exc:

            logger.exception(exc)

            result = ToolResult(
                tool=tool_call.tool,
                success=False,
                error=str(exc),
            )

        elapsed = perf_counter() - start

        logger.info(
            "Tool %s finished in %.3fs",
            tool_call.tool.value,
            elapsed,
        )

        self.context_manager.add_result(
            context,
            result,
        )

        return result

    # ---------------------------------------------------------

    def execute_many(
        self,
        *,
        context: ExecutionContext,
        tool_calls: list[ToolCall],
    ) -> list[ToolResult]:
        """
        Execute multiple tools sequentially.
        """

        results = []

        for tool_call in tool_calls:

            results.append(

                self.execute(
                    context=context,
                    tool_call=tool_call,
                )

            )

        return results

    # ---------------------------------------------------------

    def execute_plan(
        self,
        *,
        context: ExecutionContext,
        plan,
    ) -> list[ToolResult]:
        """
        Execute planner output.
        """

        results = []

        for step in plan.steps:

            tool_call = ToolCall(
                tool=step.tool,
                input=step.input,
                reasoning=step.reasoning,
            )

            result = self.execute(
                context=context,
                tool_call=tool_call,
            )

            results.append(result)

        return results

    # ---------------------------------------------------------

    def latest_result(
        self,
        context: ExecutionContext,
    ) -> ToolResult | None:

        return self.context_manager.latest_result(
            context,
        )

    # ---------------------------------------------------------

    def has_failures(
        self,
        results: list[ToolResult],
    ) -> bool:

        return any(
            not result.success
            for result in results
        )

    # ---------------------------------------------------------

    def successful_results(
        self,
        results: list[ToolResult],
    ) -> list[ToolResult]:

        return [

            result

            for result in results

            if result.success

        ]

    # ---------------------------------------------------------

    def failed_results(
        self,
        results: list[ToolResult],
    ) -> list[ToolResult]:

        return [

            result

            for result in results

            if not result.success

        ]